### ISSUE TITLE
LiveDevelopmentMultiBrowser unit test issues

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10206]
**1)** <del>The Jasmine test-runner window always logs an exception when it is first loaded, before any tests are run:</del> [console messages hidden]

<del>(because bootstrap-twipsy-mod is not loaded in the Jasmine window)</del> Fixed in #10285

**2)** Several LiveDevelopmentMultiBrowser tests fail for me with "timeout: timed out after 5000 msec waiting for livedevelopment.done.opened" (usually 2-3 tests fail per run).

**3)** The console is littered with error messages after running this test suite:

```
 [testWindow]  [node-error 10:14:11 AM] nodeSocketTransport: Socket closed, but couldn't locate client SpecRunnerUtils.js:543
runs.forEach._testWindow.console.(anonymous function) SpecRunnerUtils.js:543
handleLogEvent src/extensions/default/DebugCommands/NodeDebugUtils.js:114
trigger EventDispatcher.js:222
triggerWithArray EventDispatcher.js:260
NodeConnection._receive NodeConnection.js:479
```
(twice)

```
[testWindow]  Exception in 'base:log' listener on NodeConnection {domains: Object, _registeredModules: Array[0], _pendingInterfaceRefreshDeferreds: Array[0], _pendingCommandDeferreds: Array[0], _autoReconnect: true…}
TypeError: Cannot read property 'console' of null
    at Console.runs.forEach._testWindow.console.(anonymous function) [as log] (file:///C:/code/Brackets/brackets-app/brackets/test/spec/SpecRunnerUtils.js:544:53)
    at handleLogEvent (file:///C:/code/Brackets/brackets-app/brackets/src/extensions/default/DebugCommands/NodeDebugUtils.js:117:21)
    at NodeConnection.trigger (file:///C:/code/Brackets/brackets-app/brackets/src/utils/EventDispatcher.js:222:40)
    at Object.triggerWithArray (file:///C:/code/Brackets/brackets-app/brackets/src/utils/EventDispatcher.js:260:28)
    at NodeConnection._receive (file:///C:/code/Brackets/brackets-app/brackets/src/utils/NodeConnection.js:479:29)
```
(13 times - various listeners all with the same TypeError)

Even if these are caused by the timeouts above, it suggests the code does not fail gracefully in the event of a connection timeout.

**4)** One time this test suite seemed to get stuck with the Node process hanging onto file handles in the brackets/test/temp folder, which caused many other unit tests to fail since they were unable to clear that folder.  Restating the Node process released the file handles.  Depending on how easy it is to hit this failure case, we may want to do more to increase robustness...

**Comment by busykai** [comment]
@peterflynn, could you try the current master to see if *all* of your issues are gone? If not, we'll re-open this. Also, still need the info on the default browser you're using.

**Comment by redmunds** [comment]
Re-opening. I didn't mean to close this -- it must have auto-closed.
