### ISSUE TITLE
Error from Switching Files

### ISSUE THREAD

**Issue by jtflynnz** [adobe/brackets#10396]
A note: program seemingly functions normally, except for climbing error count. Essentially, this is the issue: When running Brackets and switching between files (also on  initial loading of file during program start), new errors populate the error indicator. This is occurs even when running without extensions. The error from the console (love the new in-program console, by the way) reads as follows:

Exception in 'activeEditorChange' listener on Object TypeError: Cannot read property 'addModeClass' of undefined TypeError: Cannot read property 'addModeClass' of undefined
    at eval (/view/ThemeManager.js:268:54)
    at j (file:///D:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///D:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at refresh (/view/ThemeManager.js:260:45)
    at eval (/view/ThemeManager.js:357:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/view/MainViewManager.js:1057:29)

It is also followed by this error, which is not counted (maybe due to apparent connection):

/utils/EventDispatcher.js:225 Assertion failed:/utils/EventDispatcher.js:225 trigger

Anyway, not a fatal issue, but persistent after reinstall of the program, so appears to be in Brackets proper (Version: Release 1.1 build 1.1.0-15558 (release ea908cae5) [with Extract]).

**Comment by MarcelGerber** [comment]
Yeah, this was my fault and was already fixed in https://github.com/adobe/brackets/pull/10236.
You won't see that error message in Brackets 1.2 any longer, and you can safely ignore it until then.

**Comment by peterflynn** [comment]
Closing as fixed (in next release, 1.2).  Note that the exception is harmless in the meantime.

**Comment by jtflynnz** [comment]
Great, thanks guys!
