### ISSUE TITLE
Extract not working in brackets

### ISSUE THREAD

**Issue by lenny247** [adobe/brackets#10424]
What is says in the title. This is what i get i the console:

/thirdparty/react.js:4356 Download the React DevTools for a better development experience: http://fb.me/react-devtools
/utils/ExtensionLoader.js:220 [Extension] failed to load C:/Users/A7749118/AppData/Roaming/Brackets/extensions/user/adobe.brackets.extract - ReferenceError: _ is not defined
/utils/ExtensionLoader.js:224 ReferenceError: _ is not defined
    at file:///C:/Users/A7749118/AppData/Roaming/Brackets/extensions/user/adobe.brackets.extract/main.js:15:14436
    at file:///C:/Users/A7749118/AppData/Roaming/Brackets/extensions/user/adobe.brackets.extract/main.js:15:14439
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.context.enable (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1519:39)
    at Object.<anonymous> (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1136:33)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:132:23
    at each (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:57:31)
    at Object.Module.enable (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1098:17)
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
/command/KeyBindingManager.js:730 Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUp
/command/KeyBindingManager.js:730 Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDown
/C:/Users/A7749118/AppData/Roaming/Brackets/extensions/user/growlscript.brackets.classcompletion/StyleRuleCache.js:92 Uncaught TypeError: Cannot read property 'split' of undefined
/C:/Users/A7749118/AppData/Roaming/Brackets/extensions/user/growlscript.brackets.classcompletion/CSSCache.js:98 Detect external changes: C:/VS_projects/KeepupMVC/branches/Q4-Updates/Keepup.MVC/Content/animals/css/explore.css

**Comment by jasonsanjose** [comment]
Looks like a duplicate of https://github.com/adobe/brackets/issues/10314

**Comment by lenny247** [comment]
yep thanks you it was the csslint extension that was causing the problem.
