### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by JCris94** [adobe/brackets#10670]
extensions/default/DebugCommands/ErrorNotification.js:125 Exception in 'activeEditorChange' listener on Object TypeError: Cannot read property 'addModeClass' of undefined TypeError: Cannot read property 'addModeClass' of undefined
    at eval (/view/ThemeManager.js:268:54)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at refresh (/view/ThemeManager.js:260:45)
    at eval (/view/ThemeManager.js:357:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/view/MainViewManager.js:1057:29)
/utils/EventDispatcher.js:225 Assertion failed:
extensions/default/DebugCommands/ErrorNotification.js:125 Exception in 'activeEditorChange' listener on Object TypeError: Cannot read property 'addModeClass' of undefined TypeError: Cannot read property 'addModeClass' of undefined
    at eval (/view/ThemeManager.js:268:54)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at refresh (/view/ThemeManager.js:260:45)
    at eval (/view/ThemeManager.js:357:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/view/MainViewManager.js:1057:29)
/utils/EventDispatcher.js:225 Assertion failed:

**Comment by prafulVaishnav** [comment]
Can you provide some details like : 1. What workflow is causing this exception? 2. Does this error go when you reload Brackets without extensions (Under Debug -> Reload Without Extensions) and repeat the workflow. 3. Version/build of Bracket you are using?

**Comment by peterflynn** [comment]
Already fixed by PR #10236, which will be part of 1.2 -- closing
