### ISSUE TITLE
unable to install brackets extension unknown internal error (ubuntu 14.10)

### ISSUE THREAD

**Issue by raminox** [adobe/brackets#10748]

**Comment by prafulVaishnav** [comment]
@raminox Can you please do troubleshoot given in https://github.com/adobe/brackets/wiki/Troubleshooting#extension-install Are you able to use Live Preview ?

**Comment by raminox** [comment]
Yeah live preview it seems working well

**Comment by prafulVaishnav** [comment]
@raminox Hii. Some steps:

1. Have you tried the troubleshoot guide given above?

2. Can you do following - 
Go to Debug -> Show Developer Tools
Go to the Console tab

If you see any error there, can you paste it here.

2. Are you able to install the extension manually i..e. by dragging the zip file.

**Comment by raminox** [comment]
## I did what you mentioned above & all i got this message
[node-error 10:28:32 AM] [Launcher] uncaught exception
at top level, exiting. Error: listen EADDRINUSE
at errnoException (net.js:901:11)
at Server._listen2 (net.js:1039:14)
at listen (net.js:1061:10)
at net.js:1135:9
at dns.js:72:18
at process._tickCallback (node.js:415:13) ErrorNotification.js:125
[node-info 10:28:32 AM] [Server] stopping NodeDebugUtils.js:114
[NodeDomain] Error loading domain "staticServer": [object Object] ErrorNotification.js:125
Failed to load resource

**Comment by jmls** [comment]
I have the same problem (on 15.04) but running within a docker container

**Comment by jmls** [comment]
was this ever fixed ? I want to be able to run brackets on a docker process - are there any readme's on how to do this ?

**Comment by wangan** [comment]
+1

**Comment by jmls** [comment]
*bump* ? Anyone ? We've got 1.6 running in a docker container, but have the same issue again. I also see that there is something in the about page .. 

![image](https://cloud.githubusercontent.com/assets/929523/11865760/09011e58-a49e-11e5-9574-185107da191e.png)

the last sentence kinda hints that there's a problem somewhere, I was just wondering if it were related

thanks

**Comment by abose** [comment]
This Usually happens when brackets cant access the network.

**Comment by jmls** [comment]
what kind of access is needed ? We're trying to get this running in docker - so the shell inside the docker container (bash) can access the outside world (npm install etc) ... so I would imagine a process started from that shell would also have access. Unless there's something being blocked somewhere .. ;) Any hints ?

**Comment by abose** [comment]
Weel I do not know that, The message (we are having trouble accessing..) is the fail handler for the ajax request.
Which means that the network access didn't go through.

**Comment by jmls** [comment]
when you say "brackets" are you talking about the client side (in the browser) or the node side ? what is port 9234 used for ? I'm wondering if docker / firewall is blocking this port  - as it may explain the other issues (help/about, install extensions, can;'t debug->show dev tools

**Comment by abose** [comment]
port 9324 is the debug port for brackets. If that is blocked, then `debug>show developer tools` will fail. It should not affect functioning of any other parts of brackets.

**Comment by shubhamkhare1** [comment]
Try this>>
>>Download .zip from site
>>unzip it
>>/opt/brackets/www/extensions/default [Follow path]
>>for default directory do chmod 777 default
>>copy ur unzipped extension file there(CAREFULLY INCLUDE ALL FILES IN ONE FOLDER)
>>Start brackets
>>WOOO! u have ur extensions.... 

- still its temp. solution>>
