### ISSUE TITLE
Extract fills developer console with deprecation warnings

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#11044]
1. Install Brackets with Extract for Brackets
2. Console is filled with Deprecation warnings such as:

``` js
 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:479:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/./ParfaitAPI.js:123:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
```

Small / easy fixes but I can't really do them myself as the extension is closed source...

**Comment by ryanstewart** [comment]
Thanks for this @petetnt. @prafulVaishnav I'll add this to the E4B work for the next release.

**Comment by petetnt** [comment]
@ryanstewart :+1:

**Comment by ficristo** [comment]
I guess we can close this now?
