### ISSUE TITLE
Brackets disappears from taskbar in Win8, flashes on &  off - live preview slow 2 update

### ISSUE THREAD

**Issue by tbarko** [adobe/brackets#11551]
Using version: Release 1.4 build 1.4.0-16380 (release 273804eb3) in Windows 8
Works fine for a while then at some undetermined point it gets "weird." Flashes briefly, disappears from the taskbar so that I have to use alt/tab to switch back and forth between it and Chrome - because I can no longer access the taskbar (from Brackets) by moving the mouse to the bottom of the screen and when in Chrome there is no Brackets icon on the taskbar anymore. Chrome then doesn't update immediately upon a change in my stylesheet, instead a get a wait cursor for a long time and often have to just cancel live preview and start it again. This is getting annoying, I would like to know what is wrong. I tried uninstalling and re-installing the latest d/l (was the same as previous anyway), but no change does the same thing - works normally for a while, then goes crazy.

**Comment by abose** [comment]
Can you try `file> enable experimental live view` ?
Also can you get the console logs at `debug>show developer tools`

**Comment by tbarko** [comment]
Thanks for the reply. Worked a few hours this morning in it and guess 
what - no problem. Then this afternoon it's back to its old tricks. 
Couldn't see how to save the console log, so I copied & pasted it into 
WordPad (attached). I saw a couple of broken links there as a result of 
this file being built (before revisions) on a Boilerplate template and I 
hadn't put some of the >js files in my js folder (and I'm not sure what 
most of them do anyway). So after I saved the log I removed the broken 
links.
    Tried experimental live view, but just got an error message telling 
me to open an html file when there was one already open. Went back to 
live preview and it previewed ok, save for the aforementioned problems.
    Thanks again,
Tom
P.S. If memory serves the program behaved in the same bizarre manner on 
one of my other computers, so it's not just this laptop. This laptop is 
a Dell Inspiron 15 3000 series with 8gb ram, if that helps. However, as 
I said it did it on my desktop or my other laptop as well, but I can't 
remember which.

On 8/7/2015 12:05 AM, Arun Bose wrote:
>
> Can you try |file> enable experimental live view| ?
> Also can you get the console logs at |debug>show developer tools|
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/adobe/brackets/issues/11551#issuecomment-128598731>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by abose** [comment]
Thanks @tbarko . I cant see the attachment as you might have replied by mail. If you face this problem again, sent the console logs directly as a reply to this comment.

**Comment by tbarko** [comment]
The 1st e-mail u sent said "Reply to this email directly or view it on GitHub." so I replied directly & attached the log as an .rtf file. It's too big for an image file. Don't think it'll help much anyway, Brackets has become more & more unstable until I am through with it!! A shame since I loved Live Preview and how it would outline the currently selected element. Very helpful. Too bad it's completely unusable. It crashed at least 6 times yesterday, losing me some work once. Today it was unstable immediately, so I decided maybe if I restart my laptop, maybe something's stuck in memory. Now it won't start at all. Windows just says it's not responding. That's it! I've wasted way too much time already fooling with this piece of crap! Guess I'll have to go back to Html-kit. I downloaded Atom & Sublime Text due to some raves by others, but couldn't find a browser preview command anywhere, let alone a live preview. Here's the log for what good it'll do, probably nothing:

/thirdparty/react.js:4486 Download the React DevTools for a better development experience: http://fb.me/react-devtools
2015-08-07 15:24:29.482/utils/DeprecationWarning.js:90 PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:548:24)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
2015-08-07 15:24:43.978/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/./ParfaitAPI.js:126:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
2015-08-07 15:24:43.978/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/./ParfaitAPI.js:127:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
2015-08-07 15:24:43.978/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/./ParfaitAPI.js:128:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
2015-08-07 15:25:13.196/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
2015-08-07 15:25:13.339/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.registerMainPanel (/./MainPanel.js:293:9)
    at _appReadyHandler (/main.js:281:19)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:284:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27220)
2015-08-07 15:25:13.343/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object._initParfaitControlsPopup [as initParfaitControlsPopup] (/./ParfaitPopup.js:112:9)
    at _appReadyHandler (/main.js:282:22)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:284:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27220)
2015-08-07 15:25:13.344/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at _appReadyHandler (/main.js:285:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:284:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27220)
    at Object.d.always (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:28096)
2015-08-07 15:25:13.346/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at _attachExtensionManagerListener (/main.js:118:9)
    at _appReadyHandler (/main.js:289:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:284:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27220)
2015-08-07 15:25:13.347/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at _setupAbandonmentEvents (/main.js:234:9)
    at _appReadyHandler (/main.js:291:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:284:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27220)
2015-08-07 15:25:13.348/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at _appReadyHandler (/main.js:294:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:284:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27220)
    at Object.d.always (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:28096)
2015-08-07 15:27:06.876http://127.0.0.1:9222/json Failed to load resource: net::ERR_CONNECTION_REFUSED
2015-08-07 15:27:22.664/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: the server responded with a status of 404 (Not Found) (url: http://127.0.0.1:60700/favicon.ico)
2015-08-07 15:35:38.926ScopeManager.js:1073 Worker: Error thrown in tern_worker:undefined is not a function
TypeError: undefined is not a function
    at infer (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1100:39)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:986:9
    at Object.BinaryExpression (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:906:15)
    at infer (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1100:39)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:986:9
    at Object.BinaryExpression (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:906:15)
    at infer (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1100:39)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:986:9
    at Object.BinaryExpression (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:906:15)
    at infer (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1100:39)
2015-08-07 15:36:27.936http://127.0.0.1:9222/json Failed to load resource: net::ERR_CONNECTION_REFUSED
2015-08-07 15:36:33.909/utils/EventDispatcher.js:224 Exception in 'styleSheetRemoved' listener on Object TypeError: Cannot read property 'canonicalizedURL' of undefined TypeError: Cannot read property 'canonicalizedURL' of undefined
    at _styleSheetRemoved (/LiveDevelopment/Agents/CSSAgent.js:164:52)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at Object.triggerWithArray (/utils/EventDispatcher.js:260:28)
    at WebSocket._onMessage (/LiveDevelopment/Inspector/Inspector.js:228:29)
2015-08-07 15:36:33.909/utils/EventDispatcher.js:225 Assertion failed:
2015-08-07 15:36:33.916/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/modernizr-2.6.2.min.js)
2015-08-07 15:36:33.986/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/plugins.js)
2015-08-07 15:36:33.986/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/main.js)
2015-08-07 15:36:56.140/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js)
2015-08-07 15:36:56.142/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/jquery-1.10.2.min.js)
2015-08-07 15:37:18.311/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://www.google-analytics.com/analytics.js)
2015-08-07 15:37:23.423/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/modernizr-2.6.2.min.js)
2015-08-07 15:37:23.431/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js)
2015-08-07 15:37:23.432/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/plugins.js)
2015-08-07 15:37:23.432/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/main.js)
2015-08-07 15:37:23.618/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/jquery-1.10.2.min.js)
2015-08-07 15:37:23.622/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://www.google-analytics.com/analytics.js)
2015-08-07 15:37:52.474/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:37:52.476/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:38:14.637/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js)
2015-08-07 15:38:36.752/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://www.google-analytics.com/analytics.js)
2015-08-07 15:39:20.953/file/FileUtils.js:283 Uncaught TypeError: Cannot read property 'lastIndexOf' of null
2015-08-07 15:39:23.569/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:39:23.570/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:39:23.572/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:39:23.619/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/modernizr-2.6.2.min.js)
2015-08-07 15:39:45.730/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js)
2015-08-07 15:40:07.920/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://www.google-analytics.com/analytics.js)
2015-08-07 15:41:18.608/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/modernizr-2.6.2.min.js)
2015-08-07 15:41:40.832/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js)
2015-08-07 15:42:03.027/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://www.google-analytics.com/analytics.js)
2015-08-07 15:46:19.375/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/modernizr-2.6.2.min.js)
2015-08-07 15:46:41.609/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js)
2015-08-07 15:47:03.839/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://www.google-analytics.com/analytics.js)
2015-08-07 15:47:18.720/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/modernizr-2.6.2.min.js)
2015-08-07 15:47:18.733/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/plugins.js)
2015-08-07 15:47:18.734/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/main.js)
2015-08-07 15:47:18.741/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:47:18.756/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:47:40.659/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js)
2015-08-07 15:47:40.662/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/jquery-1.10.2.min.js)
2015-08-07 15:47:48.085/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/modernizr-2.6.2.min.js)
2015-08-07 15:47:48.085/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js)
2015-08-07 15:47:48.086/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/plugins.js)
2015-08-07 15:47:48.086/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/main.js)
2015-08-07 15:47:48.230/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/jquery-1.10.2.min.js)
2015-08-07 15:48:02.792/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://www.google-analytics.com/analytics.js)
2015-08-07 15:48:16.879/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:48:16.880/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:48:16.881/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:48:16.930/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://spacecenter/Earth/Sites/BarkoDesign/js/vendor/modernizr-2.6.2.min.js)
2015-08-07 15:48:39.075/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js)
2015-08-07 15:48:53.014/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:48:53.015/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:48:53.039/LiveDevelopment/LiveDevelopment.js:486 Inspected frame has gone Object Object
2015-08-07 15:48:53.099/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/modernizr-2.6.2.min.js)
2015-08-07 15:48:53.113/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/plugins.js)
2015-08-07 15:48:53.113/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/main.js)
2015-08-07 15:48:53.114/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js)
2015-08-07 15:48:53.158/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file:///C:/Sites/bd/redesign/js/vendor/jquery-1.10.2.min.js)
2015-08-07 15:49:01.204/LiveDevelopment/Agents/ConsoleAgent.js:55 ConsoleAgent: Failed to load resource: net::ERR_FILE_NOT_FOUND (url: file://www.google-analytics.com/analytics.js)

**Comment by abose** [comment]
This could be an extension problem as the logs throws lots of errors from non-brackets core.
Could you go to appdata>delete brackets folder, and see if that works.
NB: This would reset brackets and all prefs/extensions/settings will be removed.

**Comment by abose** [comment]
Also enable "file>experimental live preview" as i could see brackets trying to use the old RDP way from the logs for live preview.

**Comment by tbarko** [comment]
Tried "experimental live view" as I mentioned above ("Tried experimental live view, but just got an error message telling me to open an html file when there was one already open.") - tried 3 times, got that ridiculous message every time. The only thing about the extensions is - I never installed any beyond the default ones that load with the basic install. And as I said I uninstalled it and reinstalled once already. It does the very same thing it did on the first install only it seems to be getting progressively worse. Won't even open now. Just says "not responding". This after restarting my machine because Brackets crashed 6 times the previous day. All my other programs are working fine. Brackets and Win 8 just don't get along I guess. I'll try what you suggest re: deleting the Brackets folder in AppData. Thanks for trying to help. Really liked the program, but it became too frustrating.

**Comment by tbarko** [comment]
Did what you aid: deleted the  entire Brackets folder in C:/Users/Tom/Appdata/Roaming. The program started again for the 1st time since yesterday afternoon, but as soon as I selected "open folder" it started going wacky again. After it became unresponsive I closed it. Now it won't open again even after deleting the appdata Brackets folder a 2nd time. This animated gif is an approximation of what it does when it fails to open at all and becomes unresponsive. 
![capture_006_11082015_113105](https://cloud.githubusercontent.com/assets/13682365/9206618/8962307a-402e-11e5-860d-6fcdefa6d216.gif)

**Comment by nethip** [comment]
@tbarko Sorry that you are running into this issue. This seems to be a render process,responsible for loading up the editor HTML, crash. Make sure you don't have any stray Brackets/node processes running in the task manager. Also you could restart the system, clear preferences, and then try bringing up Brackets.
