### ISSUE TITLE
Editor focus erratic and UI issues with "activation follows mouse" (x-mouse) on Windows

### ISSUE THREAD

**Issue by Kadigan** [adobe/brackets#12069]
**Brackets Version**: 1.5.0-16538

**OS**: Windows 7 Ultimate x64 SP1, English

**Extensions**: I have confirmed the issue exists when loading with "Reload without extensions" (I'm using PHP-oriented extensions only)

**Previous versions**: This is my first version of the product, so I cannot tell if it was occuring on previous versions.

**Errors**: none when the issue occurs. The only error I have in the console is "PreferencesManager.convertPreferences() has been deprecated." -- Please look to the bottom of the report for full contents of this error.

**ISSUE**: interface issues (title bar flashing), losing focus with the editor.

*NOTE: the issue is intermittent - sometimes it'll happen, sometimes it won't.*

** **
**--------------------------------**
**STEPS TO REPRODUCE**:

*METHOD 1*
- Enable "activation follows mouse" (with 0ms delay) in system preferences (a registry edit may be required) and log out/in to enable. (this only needs to happen once per user account)
- Launch Brackets
- Open a file to edit
- Alt+Tab away from the editor
- Alt+Tab back to the editor
- *(optional)* Start typing

**What I expected to happen**: I expected the editor to receive focus in its window, and I expected to be able to continue writing code from that point on. (I do this to write a bit, refresh page/reload code in test suite, and then continue)

**What actually happens**: the editor goes all "wonky", the title bar is flashing like crazy, and the keyboard focus is actually with the window that was just active (browser, terminal etc.). Sometimes the previous window will "flash through" the Brackets interface, alerting me to the error.

 Sometimes I'll be able to type one letter in (that's why there's an optional step) before this happens, and sometimes it'll happen right away.

** **
*METHOD 2*
- Enable "activation follows mouse" (with 0ms delay) in system preferences (a registry edit may be required) and log out/in to enable. (this only needs to happen once per user account)
- Launch Brackets
- Open a file to edit
- Type something in
- Hit Ctrl+S to save
- *(optional)* Start typing

**What I expected to happen**: I expected to be able to continue writing code from that point on.

**What actually happens**: the editor goes all "wonky", the title bar is flashing like crazy, and the keyboard focus is with the window directly below the Brackets interface (or with the desktop otherwise). Sometimes the window below will "flash through" the Brackets interface, alerting me to the error.

Sometimes I'll be able to type one letter in (that's why there's an optional step) before this happens, and sometimes it'll happen right away.

** **
**Steps to recover**:

Method 1: Alt+Tab out of the editor and back into the editor.

Method 2: click within the editor window / editor title bar (not where the underlying window is "flashing through".

** **
**--------------------------------**
**Comments**:

Note that I do realize that this issue, if related directly to my mouse/focus settings, probably affects only a small portion of users. (I have not tested if the issue also happens with the X-Mouse program)

It may be indicative of a deeper underlying issue within the window environment, so I felt it was better if I reported it.

Please note that this issue is preventing me from editing my code (enough to have me actually register an account on github and file a bug report!), and if it's not fixed, I will be forced to move on to other code editing software (I am currently test-driving a number of editors). The bug is absolutely devastating to my coding process.

** **
*Full error information (see top for explanation)*:

PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:548:24)

**Comment by Kadigan** [comment]
Note that I do realize that this issue, if related directly to my mouse/focus settings, probably affects only a small portion of users. (I have not tested if the issue also happens with the X-Mouse program)

It may be indicative of a deeper underlying issue within the window environment, so I felt it was better if I reported it.

Please note that this issue is preventing me from editing my code (enough to have me actually register an account on github and file a bug report!), and if it's not fixed, I will be forced to move on to other code editing software (I am currently test-driving a number of editors). The bug is absolutely devastating to my coding process.

**Comment by Kadigan** [comment]
Upon further investigation it seems that this issue -> https://github.com/adobe/brackets/issues/11131 (Brackets is losing keyboard focus) <-- could very well be related and indicate a bigger problem with window switching in general.

**Comment by Kadigan** [comment]
I would like to note that I am at this point actively using a different editor, but I am available to provide reproductions, videos, any required debug information etc. and to generally provide requested feedback in order to assist in debugging this issue.
