### ISSUE TITLE
currentFileChange listener error leads into a maximum call stack size exceeding RangeError

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#12608]
Been running into this lately. Sometimes when you go and which the file in working tree or in file tree, Brackets hangs for a long while (seconds to minutes to forever). After it recovers you'll, console is filled with errors:

```
// First error
Exception in 'currentFileChange' listener on Object {...}
RangeError: Maximum call stack size exceeded RangeError: Maximum call stack size exceeded
    at incErrorCount (file:///Applications/Brackets.app/Contents/dev/src/extensions/default/DebugCommands/ErrorNotification.js:95:9)
    at Console.window.console.error (file:///Applications/Brackets.app/Contents/dev/src/extensions/default/DebugCommands/ErrorNotification.js:124:13)
    at Object.trigger (file:///Applications/Brackets.app/Contents/dev/src/utils/EventDispatcher.js:235:25)
    at _notifyActiveEditorChanged (file:///Applications/Brackets.app/Contents/dev/src/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (file:///Applications/Brackets.app/Contents/dev/src/editor/EditorManager.js:182:9)
    at Object.trigger (file:///Applications/Brackets.app/Contents/dev/src/utils/EventDispatcher.js:233:40)
    at setActivePaneId (file:///Applications/Brackets.app/Contents/dev/src/view/MainViewManager.js:399:21)
    at _activeEditorChange (file:///Applications/Brackets.app/Contents/dev/src/view/MainViewManager.js:461:21)
    at Object.trigger (file:///Applications/Brackets.app/Contents/dev/src/utils/EventDispatcher.js:233:40)
    at _notifyActiveEditorChanged (file:///Applications/Brackets.app/Contents/dev/src/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (file:///Applications/Brackets.app/Contents/dev/src/editor/EditorManager.js:182:9)
    at Object.trigger (file:///Applications/Brackets.app/Contents/dev/src/utils/EventDispatcher.js:233:40)
    at setActivePaneId (file:///Applications/Brackets.app/Contents/dev/src/view/MainViewManager.js:399:21)
    at _activeEditorChange (file:///Applications/Brackets.app/Contents/dev/src/view/MainViewManager.js:461:21)
    at Object.trigger (file:///Applications/Brackets.app/Contents/dev/src/utils/EventDispatcher.js:233:40)
    at _notifyActiveEditorChanged (file:///Applications/Brackets.app/Contents/dev/src/editor/EditorManager.js:165:17)ErrorNotification.js:125 window.console.error

// Subsequent errors
Exception in 'currentFileChange' listener on Object RangeError: Maximum call stack size exceeded RangeError: Maximum call stack size exceeded
    at t (file:///Applications/Brackets.app/Contents/dev/src/thirdparty/lodash.js:6:249)
    at Function.<anonymous> (file:///Applications/Brackets.app/Contents/dev/src/thirdparty/lodash.js:28:229)
    at file:///Applications/Brackets.app/Contents/dev/src/language/CodeInspection.js:185:34
    at Array.reduce (native)
    at getProvidersForPath (file:///Applications/Brackets.app/Contents/dev/src/language/CodeInspection.js:184:61)
    at run (file:///Applications/Brackets.app/Contents/dev/src/language/CodeInspection.js:380:42)
    at file:///Applications/Brackets.app/Contents/dev/src/language/CodeInspection.js:530:21
    at Object.trigger (file:///Applications/Brackets.app/Contents/dev/src/utils/EventDispatcher.js:233:40)
    at setActivePaneId (file:///Applications/Brackets.app/Contents/dev/src/view/MainViewManager.js:399:21)
    at _activeEditorChange (file:///Applications/Brackets.app/Contents/dev/src/view/MainViewManager.js:461:21)
    at Object.trigger (file:///Applications/Brackets.app/Contents/dev/src/utils/EventDispatcher.js:233:40)
    at _notifyActiveEditorChanged (file:///Applications/Brackets.app/Contents/dev/src/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (file:///Applications/Brackets.app/Contents/dev/src/editor/EditorManager.js:182:9)
    at Object.trigger (file:///Applications/Brackets.app/Contents/dev/src/utils/EventDispatcher.js:233:40)
    at setActivePaneId (file:///Applications/Brackets.app/Contents/dev/src/view/MainViewManager.js:399:21)
    at _activeEditorChange (file:///Applications/Brackets.app/Contents/dev/src/view/MainViewManager.js:461:21)
...
```

For some reason Brackets goes into an endless loop of `setActivePaneId`:s and which lead to `_activeEditorChange`s.  Quite possibly an `splitViewSameDoc` error.

/cc @swmitra

**Comment by petetnt** [comment]
Haven't seen this one in a while
