### ISSUE TITLE
MacOS Hidden File "Icon" Tree Issue

### ISSUE THREAD

**Issue by Akira1138** [adobe/brackets#12694]
Hello everyone

Since last update to El-Capitan, i got the following tree issue in Brackets (see below)

![error](https://cloud.githubusercontent.com/assets/21115089/17796496/2c0645ba-65c1-11e6-9053-fabdf13a6cb2.png)

This hidden file system is created when changing the current default icon folder.

As shown in picture, this annoying "Icon" still appear even with file exclude extension, i tried several different spelling but no changes or no idea on what the correct could be. This makes all files and folders below it unavailable, meaning i cannot open them, also when switching to another folder the tree list is not automatically refreshed, have to do it manually. I think Brackets just doesn't like it :) see error report below:

`/utils/EventDispatcher.js:235 Exception in 'projectOpen' listener on Object {_eventHandlers: Object, _EventDispatcher: true, _actionCreator: ActionCreator, _RENDER_DEBOUNCE_TIME: 100}_EventDispatcher: true_RENDER_DEBOUNCE_TIME: 100_actionCreator: ActionCreator_eventHandlers: Object_setFileTreeSelectionWidth: _setFileTreeSelectionWidth(width)addClassesProvider: addClassesProvider(callback)addIconProvider: addIconProvider(callback)createNewItem: createNewItem(baseDir, initialName, skipRename, isFolder)deleteItem: deleteItem(entry)forceFinishRename: forceFinishRename()getAllFiles: getAllFiles(filter, includeWorkingSet, sort)getBaseUrl: getBaseUrl()getContext: getContext()getInitialProjectPath: getInitialProjectPath()getLanguageFilter: getLanguageFilter(languageId)getProjectRoot: getProjectRoot()getSelectedItem: getSelectedItem()isWelcomeProjectPath: isWelcomeProjectPath(path)isWithinProject: isWithinProject(absPathOrEntry)makeProjectRelativeIfPossible: makeProjectRelativeIfPossible(absPath)off: (events, fn)on: (events, fn)one: (events, fn)openProject: openProject(path)refreshFileTree: i()renameItemInline: (entry)rerenderTree: rerenderTree()setBaseUrl: setBaseUrl(projectBaseUrl)shouldShow: shouldShow(entry)showInTree: showInTree(entry)trigger: (eventName)updateWelcomeProjectPath: updateWelcomeProjectPath(path)__proto__: Object Invariant Violation: findComponentRoot(..., .0.4.$Icon
): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``. Invariant Violation: findComponentRoot(..., .0.4.$Icon
): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
    at invariant (/thirdparty/react.js:20273:15)
    at Object.ReactMount.findComponentRoot (/thirdparty/react.js:11890:47)
    at Object.ReactMount.findReactNodeByID (/thirdparty/react.js:11805:23)
    at Object.getNode (/thirdparty/react.js:11288:32)
    at Object.SimpleEventPlugin.didPutListener (/thirdparty/react.js:16415:29)
    at Object.EventPluginHub.putListener (/thirdparty/react.js:2400:20)
    at Object.wrapper [as putListener] (/thirdparty/react.js:12879:21)
    at Object.putListener (/thirdparty/react.js:6853:28)
    at CallbackQueue.assign.notifyAll (/thirdparty/react.js:889:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/thirdparty/react.js:13505:26)trigger @ /utils/EventDispatcher.js:235(anonymous function) @ /project/ProjectManager.js:926j @ thirdparty.min.js:19k.fireWith @ thirdparty.min.js:19e.(anonymous function) @ thirdparty.min.js:19(anonymous function) @ /project/ProjectManager.js:518(anonymous function) @ thirdparty.min.js:19j @ thirdparty.min.js:19k.fireWith @ thirdparty.min.js:19e.(anonymous function) @ thirdparty.min.js:19(anonymous function) @ /project/ProjectModel.js:542_applyAllCallbacks @ /filesystem/Directory.js:122(anonymous function) @ /filesystem/Directory.js:217(anonymous function) @ /filesystem/impls/appshell/AppshellFileSystem.js:304(anonymous function) @ /filesystem/impls/appshell/AppshellFileSystem.js:244(anonymous function) @ appshell:303
/utils/EventDispatcher.js:236 Assertion failed:trigger @ /utils/EventDispatcher.js:236(anonymous function) @ /project/ProjectManager.js:926j @ thirdparty.min.js:19k.fireWith @ thirdparty.min.js:19e.(anonymous function) @ thirdparty.min.js:19(anonymous function) @ /project/ProjectManager.js:518(anonymous function) @ thirdparty.min.js:19j @ thirdparty.min.js:19k.fireWith @ thirdparty.min.js:19e.(anonymous function) @ thirdparty.min.js:19(anonymous function) @ /project/ProjectModel.js:542_applyAllCallbacks @ /filesystem/Directory.js:122(anonymous function) @ /filesystem/Directory.js:217(anonymous function) @ /filesystem/impls/appshell/AppshellFileSystem.js:304(anonymous function) @ /filesystem/impls/appshell/AppshellFileSystem.js:244(anonymous function) @ appshell:303`

Any ideas ?

Thanks & Regards

**Comment by ficristo** [comment]
This is an extension problem and you should file it against the extension repository so I'm closing it.

Are you saying it worked in the past and now it doesn't?
You could try to move all your extensions but the exclude one in the disabled folder and see if there is some extensions conflict.
