### ISSUE TITLE
PreferencesManager.convertPreferences() has been deprecated.

### ISSUE THREAD

**Issue by iegik** [adobe/brackets#12775]
v1.8.2
In console shows the warning:

```
PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (file:///opt/Brackets-Electron/resources/app/www/preferences/PreferencesManager.js:323:28)
    at Object.<anonymous> (file:///opt/Brackets-Electron/resources/app/www/utils/Resizer.js:557:24)
```

**Comment by ficristo** [comment]
Fixed in https://github.com/adobe/brackets/pull/12720
