### ISSUE TITLE
Can't install extensions

### ISSUE THREAD

**Issue by s5rockhoppers** [adobe/brackets#12916]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`? **N/A**
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

When trying to install an extension or theme an error message pops up stating "Installation failed. Unknown internal error." This happens when trying to install from a URL or zip file. It will work if I download the extension manually and put it in the extensions directory however. If I try and remove the manually installed extension it will not do it. I get an error stating "Unable to remove one or more extensions: {extension name is placed here}. Brackets will still reload." Disabling does work wither although t here is no error message with that. I had Brackets 1.7 installed earlier and had no problems. I completely uninstalled 1.7 including all residual directories/extensions before installing 1.8. I am behind a firewall (at work).

### Steps to Reproduce

1. Open Brackets with extensions enabled
2. Go into extension manager.
3. Choose an extension to install
4. As soon as you click on the install button for the extension the error message will come up stating the installation failed.

**Expected behavior:** Extension is installed and Brackets is restarted if necessary.

**Actual behavior:** Error message pops up saying "Installation failed. Unknown internal error."

### Versions

Windows 7 32-bit
Brackets 1.8 (build 1.8.0-17108)

**Comment by waffledonkey** [comment]
I have the same problem.  For me 1.8 works, but only if I'm **not** behind a proxy.  If I'm behind a proxy (with the proxy preference set) it fails immediately with the error mentioned above.  1.7 works both behind a proxy or not.

Here's the entire console output (1.8, behind a proxy w/proxy pref):

`/thirdparty/react.js:6541 Download the React DevTools for a better development experience: https://fb.me/react-devtools`

`/utils/DeprecationWarning.js:88 PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:323:28)
    at Object.eval (/utils/Resizer.js:557:24)`

`/command/KeyBindingManager.js:747 Cannot assign Shift-Cmd-1 to codefolding.expand.all. It is already assigned to view.togglePanels_addBinding @ /command/KeyBindingManager.js:747`

`/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - start`

`NodeDebugUtils.js:111 [node-error 12:38:34 PM] [Launcher] uncaught exception at top level, exiting. TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:53:11)
    at TunnelingAgent.exports.request (http.js:31:10)
    at TunnelingAgent.createSocket (/Applications/Brackets.app/Contents/www/extensibility/node/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/Applications/Brackets.app/Contents/www/extensibility/node/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
    at TunnelingAgent.addRequest (/Applications/Brackets.app/Contents/www/extensibility/node/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
    at new ClientRequest (_http_client.js:158:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at Request.start (/Applications/Brackets.app/Contents/www/extensibility/node/node_modules/request/request.js:584:30)
    at Request.end (/Applications/Brackets.app/Contents/www/extensibility/node/node_modules/request/request.js:1212:28)handleLogEvent @ NodeDebugUtils.js:111`

`NodeDebugUtils.js:111 [node-info 12:38:34 PM] [Server] stopping`

`/filesystem/FileSystem.js:965 File watchers went offline!`

`/extensibility/Package.js:408 Unknown installation error cleanup`

`/utils/NodeConnection.js:84 WebSocket connection to 'ws://localhost:54181/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

`/filesystem/FileSystem.js:973 Watching disabled for /Applications/Brackets.app/Contents/samples/root/Getting Started/`

**Comment by ficristo** [comment]
If you are on a 32 bit platform could you try this workaround?
https://github.com/adobe/brackets/issues/12918#issuecomment-261337603

**Comment by ficristo** [comment]
@waffledonkey could you [run from source](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) and try this PR https://github.com/adobe/brackets/pull/12933 ?
