### ISSUE TITLE
v1.8 crashes and, in general is less stable than 1.7 it seems to me.

### ISSUE THREAD

**Issue by K-Thompson** [adobe/brackets#12918]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [Y] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [Y] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

Not a bug report, but rather a report on my experience so far using Release 1.8 build 1.8.0-17108.

I've been using Brackets daily since about sprint 36, on 2 Windows 7 computers, One with 8gb ram and the other 4gb. I uninstalled 1.7 and did "fresh" install of 1.8. Fresh in quotes because I did not delete the \users\<user>\AppData\Roaming\Bracket folder.

v1.8 has crashed everyday on the one computer after various amounts of time of use, but never in less than an hour. One the notebook, that I use during a train commute of about 45 minutes, Brackets has never crashed. My sense is, there is some type resource recovery problem. Just prior to each crash, the CPU is just about pegged to max utilization. 

WHen it crashes, the files visible in the editor close. But the frame stays open. I have to use task manager to kill the Bracket's process.

Also, code hints still do not work well, not does code completion. I've reported these issues here before.

No extensions have changed since v1.7. 

The debugger console does report these 2 errors.

main.js:210 Exception in 'activeEditorChange' listener on Object TypeError: Cannot read property 'file' of null TypeError: Cannot read property 'file' of null

main.js:210 Exception in 'currentFileChange' listener on Object TypeError: Cannot read property 'file' of null TypeError: Cannot read property 'file' of null

But they do not seem like they are responsible for the crashes, only because those errors are visible as soon as Brackets open, even prior to doing anything.

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by zaggino** [comment]
We have a tern running in a web worker, instead of a node implementation which would make more sense. That could be the culprit.

**Comment by ficristo** [comment]
@K-Thompson is your platform a 32 bit one?
If so could you try to replace the node executable you find in `C:\Program Files\Brackets` with the one you can dowload from http://nodejs.org/dist/v6.3.1/win-x86/?

For the exception you get could you try this workaround?
https://github.com/adobe/brackets/issues/12792#issuecomment-252992877

**Comment by s5rockhoppers** [comment]
That seemed to fix the problem...

**Comment by K-Thompson** [comment]
@ficristo  - no, platform is 64bits Windows 7.

For the mentioned exceptions, clearing the recent list did eliminate them - per #12792 

While I have your attention, I'll also mention that I see a lot of deprecated warnings in the debugger. Not sure if I'm an exception (due to upgrading since the sprints) or if these are common and know:

> Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.

> PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).

> Fail to nomalize Cmd-Shift-]
> main.js:196 Fail to nomalize Cmd-Shift-[

> main.js:203 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.


The 1st and 4th warning go away when extensions are disabled.  The convert preferences and command key issues remain.

**Comment by ficristo** [comment]
We use React so this is expected:
```js
Download the React DevTools for a better development experience: https://fb.me/react-devtools
```
There are some issues/PR about removing old preferences system, one removed this will disappear.
About the preferences, AFAIK they should be already converted. The deprecation is only about a feature that will go away as a remainder for extension authors who used the old preferences system.
```js
/utils/DeprecationWarning.js:88 PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:323:28)
    at Object.eval (/utils/Resizer.js:557:24)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
```

These depends on your keyboard layout, and so they can appear (I think there are already a couple of issues about it)
```js
/command/KeyBindingManager.js:578 Fail to nomalize Cmd-Shift-]
/command/KeyBindingManager.js:578 Fail to nomalize Cmd-Shift-[
```

The warnings about usage of `$().on/off()` and `Mustache` are, most likely, coming from your extensions.
There is nothing you can do but opening issue againsts them. (From the logs there should be some hint about which extension is throwing the deprecation warning)
So no, you aren't the only one who gets them

**Comment by K-Thompson** [comment]
@ficristo 

>>>The warnings about usage of $().on/off() and Mustache are, most likely, coming from your extensions.

Confirmed. I edited my comment and removed them before I saw your reply.

**Comment by nicksoph** [comment]
replacement of node version - worked for me on a 32bit win10 machine

**Comment by phamnutuyetan** [comment]
@ficristo thanks due, it works for me

**Comment by ficristo** [comment]
You can try https://github.com/adobe/brackets/releases/tag/release-1.9-prerelease-2 were the win32 bit is fixed. And maybe also fixes the crashes.
