### ISSUE TITLE
Brackets produces several errors during startup.

### ISSUE THREAD

**Issue by BobbyBabes** [adobe/brackets#12983]
### Prerequisites

- [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
- [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
- [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

Brackets produces several errors during startup.
Node module chokidar : Cannot find module.
Module JavaScriptCodeHints does not exist.

Errors with all extensions disabled in the extension manager (first screenshot).
Errors with all extensions disabled in the extension manager and Shift+F5 (second screenshot).

This happens with and without folder and files opened in Brackets.

![brackets-startup-errors-all-extensions-disabled-in-extension-manager](https://cloud.githubusercontent.com/assets/22870070/21233333/0fa6a226-c2ef-11e6-88e2-438fc84ef8e7.png)

![brackets-startup-errors-all-extensions-disabled-in-extension-manager-and-shift-plus-f5](https://cloud.githubusercontent.com/assets/22870070/21233356/1fe62fd0-c2ef-11e6-86a8-0e3f1a896cf9.png)

**EDIT:** The folder and file status at the paths of the error messages :

![brackets-startup-errors-files-and-folders-related-to-startup-errors](https://cloud.githubusercontent.com/assets/22870070/21265362/58d517a4-c3a1-11e6-926d-d0fad60271b5.png)

### Steps to Reproduce

1. Disable all extensions in the extension manager.
2. Create a folder named Empty (or whatever) somewhere, and leave it empty.
3. Open the folder named Empty to close all open files and folders and start Brackets without.
4. Close Brackets.
5. Start Brackets without any files and folders opened and wait until it's fully started.
6. Hit F12 to open the console.
7. See errors displayed in the console. (first screenshot)
8. Clear the console.
9. Hit Shift + F5 to reload without extensions.
10. Watch the errors build up again in the console. The first error (red text) is flashed and removed.

**Expected behavior:** No errors in the console.

**Actual behavior:** Copy+Paste of what can be seen in the second screenshot :
```
rendered file:///opt/brackets/www/styles/brackets.less successfully. less-2.5.1.min.js:13
css for file:///opt/brackets/www/styles/brackets.less generated in 1235ms less-2.5.1.min.js:13
less has finished. css generated in 1235ms less-2.5.1.min.js:13
Download the React DevTools for a better development experience: https://fb.me/react-devtools react.js:6541
PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (file:///opt/brackets/www/preferences/PreferencesManager.js:323:28)
    at Object.<anonymous> (file:///opt/brackets/www/utils/Resizer.js:557:24) DeprecationWarning.js:88
Brackets reloaded with extensions disabled DocumentCommandHandlers.js:1698
[NodeDomain] Error loading domain "fileWatcher": Unable to load one of the modules: /opt/brackets/www/./filesystem/impls/appshell/node/FileWatcherDomain, reason: Cannot find module 'chokidar' NodeDomain.js:144
Failed to load resource file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/node_modules/acorn/dist/acorn.js
[Extension] failed to load /opt/brackets/www/extensions/default/JavaScriptCodeHints - Module does not exist: file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/node_modules/acorn/dist/acorn.js ExtensionLoader.js:220
Failed to load resource file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/node_modules/acorn/dist/acorn_loose.js
Failed to watch root:  /home/robert/Documents/Empty/ Unable to load one of the modules: /opt/brackets/www/./filesystem/impls/appshell/node/FileWatcherDomain, reason: Cannot find module 'chokidar' FileSystem.js:904
Error watching project root:  /home/robert/Documents/Empty/ Unable to load one of the modules: /opt/brackets/www/./filesystem/impls/appshell/node/FileWatcherDomain, reason: Cannot find module 'chokidar' ProjectManager.js:748
Fail to nomalize Cmd-Shift-] KeyBindingManager.js:578
Fail to nomalize Cmd-Shift-[ KeyBindingManager.js:578
NodeSocketTransport - start NodeSocketTransport.js:84
```

### Versions

**OS:** Arch Linux
**OS version:** Linux 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
**Brackets version:**  Release 1.8 experimental build 1.8.0-0
The page of the package : https://aur.archlinux.org/packages/brackets/

**Comment by BobbyBabes** [comment]
Reason for closing :

Only these Linux distros are supported.
> ## System Requirements
>Linux Ubuntu 12.04 or newer (x32 and x64)
Debian Linux 8 or newer (for Debian 7 compatibility see issue #4816)
— https://github.com/adobe/brackets/wiki/Troubleshooting
