### ISSUE TITLE
Whenever I am in an html file with live preview on, the blue highlighter does not work 

### ISSUE THREAD

**Issue by cab12** [adobe/brackets#13046]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?

**Yes.** 

* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?

**Yes. I only found an issue when someone was using a CSS file (blue highlighter works in CSS file) not the html file.**

* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

**Yes. I tried uninstalling (all files and registry's).**

### Description
**Go to live preview no blue highlight when using html file but if I switch to the CSS file the blue highlighter works fine.**

### Steps to Reproduce

Open Brackets.
Open working folder
Open html file (making sure its a work file)
Go to live preview no blue highlight when using html but if I switch to the CSS file the blue highlighter works fine.

**Expected behavior: Blue highlighter to highlight the class or div I want to change

**Actual behavior: Go to live preview no blue highlight when using html but if I switch to the CSS file the blue highlighter works fine.

Brackets Version: 1.8 

Windows 10

**Comment by petetnt** [comment]
Hi @cab12, 

sorry for the late response. Are you still able to replicate the issue? 

If you are, could you open up the developer tools (Debug -> Show Developer Tools -> Console) and see if any errors popup when live previewing a HTML file?

**Comment by murrayLuke** [comment]
I'm running into the same issue on MacOS with Chrome as my default browser. I am running the most recent version of brackets (1.8), and I get the following exceptions in my developer console.


/utils/EventDispatcher.js:231 Exception in 'styleSheetRemoved' listener on Object TypeError: Cannot read property 'canonicalizedURL' of undefined TypeError: Cannot read property 'canonicalizedURL' of undefined
    at _styleSheetRemoved (/LiveDevelopment/Agents/CSSAgent.js:161:52)
    at Object.trigger (/utils/EventDispatcher.js:229:40)
    at Object.triggerWithArray (/utils/EventDispatcher.js:267:28)
    at WebSocket._onMessage (/LiveDevelopment/Inspector/Inspector.js:226:29)trigger @ /utils/EventDispatcher.js:231
/utils/EventDispatcher.js:232 Assertion failed:trigger @ /utils/EventDispatcher.js:232
/LiveDevelopment/Inspector/Inspector.js:262 GET http://127.0.0.1:9222/json net::ERR_CONNECTION_REFUSEDgetDebuggableWindows @ /LiveDevelopment/Inspector/Inspector.js:262connectToURL @ /LiveDevelopment/Inspector/Inspector.js:328_openInterstitialPage @ /LiveDevelopment/LiveDevelopment.js:1132_doLaunchAfterServerReady @ /LiveDevelopment/LiveDevelopment.js:1244(anonymous function) @ /LiveDevelopment/LiveDevelopment.js:1365j @ thirdparty.min.js:19k.add @ thirdparty.min.js:19(anonymous function) @ /LiveDevelopment/LiveDevelopment.js:1364j @ thirdparty.min.js:19k.add @ thirdparty.min.js:19open @ /LiveDevelopment/LiveDevelopment.js:1349_handleGoLiveCommand @ /LiveDevelopment/main.js:166onGoLive @ /LiveDevelopment/main.js:206n.event.dispatch @ thirdparty.min.js:20r.handle @ thirdparty.min.js:20
/utils/EventDispatcher.js:231 Exception in 'styleSheetRemoved' listener on Object {_EventDispatcher: true, _eventHandlers: Object}_EventDispatcher: true_eventHandlers: ObjectaddRule: ()disable: ()enable: ()forcePseudoState: ()getAllStyleSheets: ()getComputedStyleForNode: ()getInlineStylesForNode: ()getMatchedStylesForNode: ()getNamedFlowCollection: ()getPlatformFontsForNode: ()getStyleSheet: ()getStyleSheetText: ()getSupportedCSSProperties: ()off: (events, fn)on: (events, fn)one: (events, fn)setPropertyText: ()setRuleSelector: ()setStyleSheetText: ()setStyleText: ()toggleProperty: ()trigger: (eventName)__proto__: Object TypeError: Cannot read property 'canonicalizedURL' of undefined TypeError: Cannot read property 'canonicalizedURL' of undefined
    at _styleSheetRemoved (/LiveDevelopment/Agents/CSSAgent.js:161:52)
    at Object.trigger (/utils/EventDispatcher.js:229:40)
    at Object.triggerWithArray (/utils/EventDispatcher.js:267:28)
    at WebSocket._onMessage (/LiveDevelopment/Inspector/Inspector.js:226:29)trigger @ /utils/EventDispatcher.js:231triggerWithArray @ /utils/EventDispatcher.js:267_onMessage @ /LiveDevelopment/Inspector/Inspector.js:226
/utils/EventDispatcher.js:232 Assertion failed:trigger @ /utils/EventDispatcher.js:232triggerWithArray @ /utils/EventDispatcher.js:267_onMessage @ /LiveDevelopment/Inspector/Inspector.js:226

**Comment by petetnt** [comment]
Thanks for the error message @murrayLuke!

There's some similar issues around that particular bug, some of which were solved by removing a certain extensions. Does this occur to you if you `Debug -> Launch Without Extensions`?

**Comment by murrayLuke** [comment]
yes. I get the following error messages when I launch without extensions. If it helps you track down the bug I am running OSsierra version 10.12.3, my version of Chrome is 56.0.2924.76 and my brackets version is Release 1.8 build 1.8.0-17108. I am not a power user of brackets so I don't have any extensions installed, the only thing I could image is causing this issue, is that I installed brackets through homebrew cask.

/LiveDevelopment/Inspector/Inspector.js:262 GET http://127.0.0.1:9222/json net::ERR_CONNECTION_REFUSEDgetDebuggableWindows @ /LiveDevelopment/Inspector/Inspector.js:262connectToURL @ /LiveDevelopment/Inspector/Inspector.js:328_openInterstitialPage @ /LiveDevelopment/LiveDevelopment.js:1132_doLaunchAfterServerReady @ /LiveDevelopment/LiveDevelopment.js:1244(anonymous function) @ /LiveDevelopment/LiveDevelopment.js:1365j @ thirdparty.min.js:19k.add @ thirdparty.min.js:19(anonymous function) @ /LiveDevelopment/LiveDevelopment.js:1364j @ thirdparty.min.js:19k.add @ thirdparty.min.js:19open @ /LiveDevelopment/LiveDevelopment.js:1349_handleGoLiveCommand @ /LiveDevelopment/main.js:166onGoLive @ /LiveDevelopment/main.js:206n.event.dispatch @ thirdparty.min.js:20r.handle @ thirdparty.min.js:20
/utils/EventDispatcher.js:231 Exception in 'styleSheetRemoved' listener on Object {_EventDispatcher: true, _eventHandlers: Object} TypeError: Cannot read property 'canonicalizedURL' of undefined TypeError: Cannot read property 'canonicalizedURL' of undefined
    at _styleSheetRemoved (/LiveDevelopment/Agents/CSSAgent.js:161:52)
    at Object.trigger (/utils/EventDispatcher.js:229:40)
    at Object.triggerWithArray (/utils/EventDispatcher.js:267:28)
    at WebSocket._onMessage (/LiveDevelopment/Inspector/Inspector.js:226:29)trigger @ /utils/EventDispatcher.js:231triggerWithArray @ /utils/EventDispatcher.js:267_onMessage @ /LiveDevelopment/Inspector/Inspector.js:226
/utils/EventDispatcher.js:232 Assertion failed:trigger @ /utils/EventDispatcher.js:232triggerWithArray @ /utils/EventDispatcher.js:267_onMessage @ /LiveDevelopment/Inspector/Inspector.js:226
