### ISSUE TITLE
Extensions are throwing errors in Brackets 1.11

### ISSUE THREAD

**Issue by bitpulsar** [adobe/brackets#13756]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [X] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description
After upgrading Brackets to version 1.11 start getting errors:

- Immediately after start:
```javascript
Uncaught TypeError: Cannot read property 'line' of undefined        NavigationProvider.js:200 
```
- and next when I click on any file or folder in Brackets it throws:
```javascript
ErrorNotification.js:122 Exception in 'activeEditorChange' listener on Object {_eventHandlers: Object, _EventDispatcher: true} TypeError: Cannot read property 'line' of undefined TypeError: Cannot read property 'line' of undefined
    at NavigationFrame._createMarkers (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/NavigationAndHistory/NavigationProvider.js:200:27)
    at new NavigationFrame (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/NavigationAndHistory/NavigationProvider.js:142:14)
    at _captureFrame (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/NavigationAndHistory/NavigationProvider.js:440:36)
    at _handleActiveEditorChange (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/NavigationAndHistory/NavigationProvider.js:525:13)
    at Object.trigger (/utils/EventDispatcher.js:229:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:161:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:178:9)
    at Object.trigger (/utils/EventDispatcher.js:229:40)
    at eval (/view/MainViewManager.js:1120:29)
    at Pane.trigger (/utils/EventDispatcher.js:229:40)window.console.error @ ErrorNotification.js:122trigger @ /utils/EventDispatcher.js:231_notifyActiveEditorChanged @ /editor/EditorManager.js:161_handleCurrentFileChange @ /editor/EditorManager.js:178trigger @ /utils/EventDispatcher.js:229(anonymous function) @ /view/MainViewManager.js:1120trigger @ /utils/EventDispatcher.js:229Pane._notifyCurrentViewChange @ /view/Pane.js:896Pane.showView @ /view/Pane.js:1208_showEditor @ /editor/EditorManager.js:567openDocument @ /editor/EditorManager.js:639_edit @ /view/MainViewManager.js:1212(anonymous function) @ /view/MainViewManager.js:1277j @ thirdparty.min.js:19k.add @ thirdparty.min.js:19_open @ /view/MainViewManager.js:1275_doOpen @ /document/DocumentCommandHandlers.js:341_doOpenWithOptionalPath @ /document/DocumentCommandHandlers.js:411handleFileOpen @ /document/DocumentCommandHandlers.js:468handleDocumentOpen @ /document/DocumentCommandHandlers.js:517Command.execute @ /command/CommandManager.js:93execute @ /command/CommandManager.js:287openAndSelectDocument @ /project/FileViewController.js:185(anonymous function) @ /project/ProjectManager.js:248trigger @ /utils/EventDispatcher.js:229ProjectModel.setSelected @ /project/ProjectModel.js:706ActionCreator.setSelected @ /project/ProjectManager.js:272Preact.createFactory.Preact.createClass.handleClick @ /project/FileTreeView.js:446d @ /thirdparty/preact/preact.js:1
/utils/EventDispatcher.js:232 Assertion failed:
```

### Steps to Reproduce
1. Open Brackets
2. Open folder with project

**Expected behavior:** Shouldn't throw any errors.

**Actual behavior:** Throw error after start and every time I click on another file/folder in Brackets .

### Versions

Windows 7 64 bit.
Brackets 1.11

**Comment by petetnt** [comment]
Thanks for reporting @bitpulsar, could you post your Health Report under Debug -> Health Report

**Comment by bitpulsar** [comment]
Hi! Sorry for the delay. In Brackets version which I have Health Report is under Help -> Health Report.

```json
{
    "snapshotTime": 1507324463725,
    "os": "win",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.11.0.0 Chrome/49.0.2623.110 Safari/537.36",
    "osLanguage": "pl-PL",
    "bracketsLanguage": "en",
    "bracketsVersion": "1.11.0-17524",
    "fileStats": {
        "openedFileExt": {
            "js": 4,
            "html": 2,
            "json": 1
        },
        "workingSetFileExt": {
            "js": 1
        },
        "openedFileEncoding": {
            "UTF-8": 7
        }
    },
    "ProjectDetails": {
        "prj320962764": {
            "numFiles": 2580,
            "cacheSize": 12222405
        }
    },
    "projectLoadTimes": ":242",
    "fileOpenTimes": ":606",
    "ModuleDepsResolved": 789959,
    "AppStartupTime": 792268,
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": [
        {
            "name": "raven",
            "version": "1.0.7"
        },
        {
            "name": "sachin.gotodefinition",
            "version": "1.0.5"
        },
        {
            "name": "brackets-glsl",
            "version": "0.0.3"
        },
        {
            "name": "jquinter",
            "version": "0.3.3"
        },
        {
            "name": "brackets-php-syntax-hint",
            "version": "1.1.6"
        },
        {
            "name": "mikailcolak.brackets-color-picker",
            "version": "0.1.3"
        },
        {
            "name": "le717.html-skeleton",
            "version": "1.4.3"
        },
        {
            "name": "talmand.html-templates",
            "version": "1.3.5"
        },
        {
            "name": "hirse.beautify",
            "version": "1.0.2"
        }
    ],
    "bracketsTheme": "dark-theme",
    "uuid": "315b-f8bc-b07e-4f08-a2a2",
    "olderuuid": "4f6c6769-4281-4286-9adf-e0ac0890eae4"
}
```
I hope this is what you need. Thank you for replying so quickly.
