### ISSUE TITLE
Contents of folder not shown in file tree

### ISSUE THREAD

**Issue by e553y** [adobe/brackets#14581]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

File tree is not visible on the left pane.
Even though there are files inside the opened folder, they will now be shown under the folder name on the file tree. Only the folder name is shown.  

### Steps to Reproduce

1. Open up any folder containing files. 

**Expected behavior:** 
Expected the contents of the active folder be shown on the file tree.

**Actual behavior:** 
Nothing is displayed under the folder name on the file tree.
### Versions
OS: Ubuntu 18.04.1 LTS
Brackets: Release 1.13 build 1.13.0-17696 (release 49d29a8bc)

**Comment by kenzo44** [comment]
Have you tried this with a different project?

**Comment by ShumailAhmed123** [comment]
Hi, 

I am new to GitHub and I am computer science student. I would like to contribute in something. Please can some one help me  or guide me to contribute? 

Thanks

**Comment by e553y** [comment]
I have tried it with several projects the results are the same. The
folder/file tree is never shown

**Comment by LKPridgeon** [comment]
Hi, 
I'm also experiencing this issue on all projects. In my case the issue occurs when adding/removing files/directories via the sidebar. When I add a directory/file outside of brackets then refresh it seems to repopulate. 

When I look at the brackets debug console:

ErrorNotification.js:122 Exception in 'projectOpen' listener on Object RangeError: Invalid language tag: c RangeError: Invalid language tag: c
    at new Collator (native)
    at String.localeCompare (native)
    at eval (/file/FileUtils.js:450:30)
    at cmpNames (/file/FileUtils.js:475:20)
    at Object.compareFilenames (/file/FileUtils.js:478:55)
    at _dirsFirstCompare (/project/FileTreeView.js:675:34)
    at eval (/thirdparty/immutable.js:3479:42)
    at Array.sort (native)
    at sortFactory (/thirdparty/immutable.js:3479:13)
    at ToIndexedSequence.sort (/thirdparty/immutable.js:4442:26)window.console.error @ ErrorNotification.js:122
EventDispatcher.js:232 Assertion failed:trigger @ EventDispatcher.js:232
ErrorNotification.js:122 Exception in 'change' listener on Preference RangeError: Invalid language tag: c RangeError: Invalid language tag: c
    at new Collator (native)
    at String.localeCompare (native)
    at eval (/file/FileUtils.js:450:30)
    at cmpNames (/file/FileUtils.js:475:20)
    at Object.compareFilenames (/file/FileUtils.js:478:55)
    at _dirsFirstCompare (/project/FileTreeView.js:675:34)
    at eval (/thirdparty/immutable.js:3479:42)
    at Array.sort (native)
    at sortFactory (/thirdparty/immutable.js:3479:13)
    at ToIndexedSequence.sort (/thirdparty/immutable.js:4442:26)window.console.error @ ErrorNotification.js:122
EventDispatcher.js:232 Assertion failed:trigger @ EventDispatcher.js:232
KeyBindingManager.js:578 Failed to normalize Cmd-Shift-]
KeyBindingManager.js:578 Failed to normalize Cmd-Shift-[
NodeSocketTransport.js:84 NodeSocketTransport - start
ErrorNotification.js:122 Cannot assign Ctrl-R to refactoring.renamereference. It is already assigned to refactoring.renamereferencewindow.console.error @ ErrorNotification.js:122
FileUtils.js:450 Uncaught RangeError: Invalid language tag: c
FileSystem.js:967 Failed to watch root:  /home/lkpridgeon/Documents/foldhill/laughingdog/subscriptions/ Max connection attempts reached
ErrorNotification.js:122 Error watching project root:  /home/lkpridgeon/Documents/foldhill/laughingdog/subscriptions/ Max connection attempts reached

This was with extensions disabled. 
Ubuntu 18.04.1 LTS
Brackets 1.13 build 1.13.0-17696 (Thu Jun 14 2018)

**Comment by LKPridgeon** [comment]
This could be to do with ubuntu 18.04.1 LTS using libcurl 4 instead of 3.

**Comment by srlopez** [comment]
I have the same problem on Ubuntu Budgie 18.10
```
santi@metabook:~/zResponsive$ uname -a
Linux metabook 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
with Brackets version:
```
Release 1.13 build 1.13.0-17696 (release 49d29a8bc) 
build timestamp: Thu Jun 14 2018 07:06:30 GMT+0000
```
Just open Brackets, installed as snap, and nothing in selected folder.
On the console the folllowing errors.
![screenshot from 2018-12-03 18-34-59](https://user-images.githubusercontent.com/94729/49391185-40f12500-f72b-11e8-86a9-b0bbe3d1b147.png)

If i try to launch Brackets from the command line:
```
santi@metabook:~/Desktop/Plaiaundi/LEN MAR/zResponsive$ brackets
[1203/184342:ERROR:browser_main_loop.cc(261)] Gtk: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "atk-bridge"
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig error: line 6: invalid attribute 'translate'
Fontconfig error: line 6: invalid attribute 'selector'
Fontconfig error: line 7: invalid attribute 'xmlns:its'
Fontconfig error: line 7: invalid attribute 'version'
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
... lots of Fontconfig warning and errors
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load default config file
[1203/184359:ERROR:browser_main_loop.cc(261)] Gtk: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)
[1203/184359:ERROR:browser_main_loop.cc(261)] Gtk: Loading IM context type 'ibus' failed
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_log_structured_standard
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[1203/184401:ERROR:browser_main_loop.cc(261)] Gtk: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)
[1203/184401:ERROR:browser_main_loop.cc(261)] Gtk: Loading IM context type 'ibus' failed

```

**Comment by joao-a-cruz** [comment]
Having the exact same issue

Ubuntu 18.04.1 LTS
brackets Release 1.13 build 1.13.0-17696 (release 49d29a8bc)

**Comment by brandonschabell** [comment]
As a workaround, you can run the following command in the devtools console for Brackets:
`global.require.s.contexts._.config.locale = "en"`

**Comment by mackomando** [comment]
I had the same issue and for me it seems to occur when the language is set to 'system default'. So I went to Debug -> Switch Language menu and choose english, and it solve the issue. I tried with several other languages and it works perfectly.

**Comment by Cvilec** [comment]
@mackomando 
your solution helped me solve the same issue, thank you!!

**Comment by mackomando** [comment]
I am glad I could help

**Comment by birozz** [comment]
global.require.s.contexts._.config.locale = "en" 
results in 
VM812:1 Uncaught ReferenceError: global is not defined(…)(anonymous function) @ VM812:1
ls

**Comment by shubhsnov** [comment]
@srlopez @mackomando @birozz 
I see the following error listed in the CLI logs pasted above:
> Gtk: Locale not supported by C library

Seems like an issue with locales, where Strings.localeCompare fails on execution.

A cursory glance on google yields this result: https://askubuntu.com/questions/359753/gtk-warning-locale-not-supported-by-c-library-when-starting-apps-from-th

Can somebody try the solution to fix the locales shown in the link above and see if it solves the issue?

Thanks.

**Comment by guthhm** [comment]
@shubhsnov 

> Can somebody try the solution to fix the locales shown in the link above and see if it solves the issue?

I had the exactly same issue with files tree and tried following some steps in the link you gave. It worked.
First:
`sudo apt-get purge locales`
Then:
`sudo aptitude install locales`
Last:
`sudo dpkg-reconfigure locales`

> This rids the system of locales, then re-installs locales and downgrades libc6 from 2.19 to 2.13 which is the issue. Then configures locales again.

Just have in mind that some applications can be affected by downgrading this lib. Hope it could help.

**Comment by eyadfareh** [comment]
debug > switch language > any language

**Comment by Sajjad-s** [comment]
@mackomando 
Thanks i had same issue but your solution was the answer ...

**Comment by chypmonk** [comment]
Thanks, Mackomando - That fixed it for me!

**Comment by CodePint** [comment]
Just been hit with this issue and spent longer than i care to admit trying to find the solution.
Is there a reason a bugfix has not been put in place as i can this was first raised the better part of a decade ago (2013) here:  https://github.com/adobe/brackets/issues/5292

I am using a recent version of brackets: 1.14 build 1.14.1-1775 (2019 release)

As a naive fix that you can cat the contents of the system language and set it automatically.

I am still getting errors when launching from terminal

`[0123/144752:ERROR:browser_main_loop.cc(261)] Gtk: Locale not supported by C library.
	Using the fallback 'C' locale.
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
[0123/144752:ERROR:gconf_listener.cc(117)] Error with gconf key '/apps/metacity/general': Failed to activate configuration server: The name org.gnome.GConf was not provided by any .service files
`

looks like the root issue is caused by this:
https://askubuntu.com/questions/359753/gtk-warning-locale-not-supported-by-c-library-when-starting-apps-from-th

why not automatically run the recommended fix here if the error occurs or on install?

**Comment by CodePint** [comment]
After several hours of googling, it seems this is an endemic issue with debian/ubuntu...rather than brackets itself.

And no one seems to have a consistent solution that actually works. Its quite unbelievable to be honest.

I have tried every which way of changing locales and regenerating language packages 
Anyone care to provide further input?

**Comment by JJ-ind** [comment]
> I had the same issue and for me it seems to occur when the language is set to 'system default'. So I went to Debug -> Switch Language menu and choose english, and it solve the issue. I tried with several other languages and it works perfectly.

This Thing Works

**Comment by Aakrity1105** [comment]
thank you so much @JJ-ind ... I had the same issue and your solution worked for me...!!

**Comment by cue8ig** [comment]
> I had the same issue and for me it seems to occur when the language is set to 'system default'. So I went to Debug -> Switch Language menu and choose english, and it solve the issue. I tried with several other languages and it works perfectly.



> I had the same issue and for me it seems to occur when the language is set to 'system default'. So I went to Debug -> Switch Language menu and choose english, and it solve the issue. I tried with several other languages and it works perfectly.

Works like magic!

**Comment by chypmonk** [comment]
I fixed it a while back and I can't remember what I did - your answer sounds familiar.   Whatever the case, it's working ok now.
Thanks for the tip -

Susan

    On Wednesday, October 21, 2020, 4:37:24 AM EDT, JakubJanda <notifications@github.com> wrote:  
 
 



I had the same issue and for me it seems to occur when the language is set to 'system default'. So I went to Debug -> Switch Language menu and choose english, and it solve the issue. I tried with several other languages and it works perfectly.



I had the same issue and for me it seems to occur when the language is set to 'system default'. So I went to Debug -> Switch Language menu and choose english, and it solve the issue. I tried with several other languages and it works perfectly.


Works like magic!

**Comment by brutalcrozt** [comment]
I am on Linux Mint 20.1 Cinnamon with 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

brackets:
Release 1.14 build 1.14.1-17752 (release-1.14.1 959fed135) 
build timestamp: Thu Nov 28 2019 08:58:11 GMT+0000

which installed with snap. which is not the lastest strangely enough!!
on GitHub and the official blog, it should be 1.14.2.

I think #2794 is similar to this, but I am just guessing.

@JJ-ind yeah but it's not the point, it would come when you annoyed because you face another problem when you trying to develop an app (which theoretically solving a problem). 

@chypmonk Are you the dev? I mean someone with maintainer authority? 

@CodePint Thanks for digging deeper :smile: It very useful when someone wants to submit a PR. Also, your 'naive fix' is far better than no fix at all. But let's hear from the maintainer. I hope a PR is merged before future release :)

**Comment by chypmonk** [comment]
HI Adi -
I am not a dev, just a programmer, who asked a question a while back.  My file  tree was not showing up because of a setting in the 'navigate' tool bar, I think - I got it to work by checking something in settings.
Good luck -
Chypmonk
   On Monday, February 15, 2021, 12:01:33 AM EST, Adi Prasetyo <notifications@github.com> wrote:  
 
 


I am on Linux Mint 20.1 Cinnamon with 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

brackets:
Release 1.14 build 1.14.1-17752 (release-1.14.1 959fed1)
build timestamp: Thu Nov 28 2019 08:58:11 GMT+0000

which installed with snap. which is not the lastest strangely enough!!
on GitHub and the official blog, it should be 1.14.2.

I think #2794 is similar to this, but I am just guessing.

@JJ-ind yeah but it's not the point, it would come when you annoyed because you face another problem when you trying to develop an app (which theoretically solving a problem).

@chypmonk Are you the dev? I mean someone with maintainer authority?

@CodePint Thanks for digging deeper 😄 It very useful when someone wants to submit a PR. Also, your 'naive fix' is far better than no fix at all. But let's hear from the maintainer. I hope a PR is merged before future release :)
