### ISSUE TITLE
building brackets in centos

### ISSUE THREAD

**Issue by sanazsoleimani** [adobe/brackets#14845]
### Prerequisites

Did i tried `alien` to convert `.deb` package to `.rpm`? `YES but didnt worked too`
Did i tried `AppImage` version? YES, but i dont want to use that version
  
### Description
i've already have brackets 1.8 installed on my machine, but spent few days to figure out how to install *latest version* of brackets on my `CentOS 7` machine.

so i started with [building from source guide](https://github.com/adobe/brackets/wiki/Building-Brackets-Releases), and after installing `nodejs`, tried to build package with typing `npm install` in directory of source code, and here is what i get:
```
> phantomjs@1.9.18 install /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: socket hang up
    at createHangUpError (_http_client.js:268:15)
    at TLSSocket.socketOnEnd (_http_client.js:360:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Please report this full log at https://github.com/Medium/phantomjs
Brackets@1.12.0-0 /path/to/brackets-source/needsLIBCF/brackets-release-1.12
├── abbrev@1.1.0 
 ...
└── zlib-browserify@0.0.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN Brackets@1.12.0-0 No license field.
npm ERR! Linux 3.10.0-957.27.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/brackets-source/needsLIBCF/brackets-release-1.12/npm-debug.log

```

and here is the `npm-debug.log` content:
```
90045 silly preinstall underscore.string@2.3.3 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/underscore.string-94b95986
90046 info lifecycle underscore.string@2.3.3~preinstall: underscore.string@2.3.3
90047 silly preinstall grunt-legacy-log-utils@0.1.1 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/grunt-legacy-log-utils-4d40bd4a
90048 info lifecycle grunt-legacy-log-utils@0.1.1~preinstall: grunt-legacy-log-utils@0.1.1
90049 silly preinstall lodash@2.4.2 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/lodash-083cc4b6
90050 info lifecycle lodash@2.4.2~preinstall: lodash@2.4.2
90051 silly preinstall underscore.string@2.3.3 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/underscore.string-e30a42d0
90052 info lifecycle underscore.string@2.3.3~preinstall: underscore.string@2.3.3
90053 silly preinstall async@0.1.22 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/async-62ff002d
90054 info lifecycle async@0.1.22~preinstall: async@0.1.22
90055 silly preinstall lodash@0.9.2 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/lodash-423c5bc7
90056 info lifecycle lodash@0.9.2~preinstall: lodash@0.9.2
91523 silly lifecycle cli-width@2.1.0~preinstall: no script for preinstall, continuing
91524 silly lifecycle wordwrap@0.0.2~preinstall: no script for preinstall, continuing
91525 silly lifecycle co@4.6.0~preinstall: no script for preinstall, continuing
91526 silly lifecycle code-point-at@1.1.0~preinstall: no script for preinstall, continuing
91527 silly lifecycle coffee-script@1.3.3~preinstall: no script for preinstall, continuing
91528 silly lifecycle colors@0.6.2~preinstall: no script for preinstall, continuing
91529 silly lifecycle commander@2.11.0~preinstall: no script for preinstall, continuing
91530 silly lifecycle concat-map@0.0.1~preinstall: no script for preinstall, continuing
91531 silly lifecycle brace-expansion@1.1.8~preinstall: no script for preinstall, continuing
91532 silly lifecycle constants-browserify@1.0.0~preinstall: no script for preinstall, continuing
91533 silly lifecycle content-type@1.0.2~preinstall: no script for preinstall, continuing
91534 silly lifecycle core-util-is@1.0.2~preinstall: no script for preinstall, continuing
91535 silly lifecycle ctype@0.5.3~preinstall: no script for preinstall, continuing
91536 silly lifecycle assert-plus@1.0.0~preinstall: no script for preinstall, continuing
91537 silly lifecycle dashdash@1.14.1~preinstall: no script for preinstall, continuing
91538 silly lifecycle date-now@0.1.4~preinstall: no script for preinstall, continuing
91539 silly lifecycle console-browserify@1.1.0~preinstall: no script for preinstall, continuing
91540 silly lifecycle dateformat@1.0.2-1.2.3~preinstall: no script for preinstall, continuing
91541 silly lifecycle decamelize@1.2.0~preinstall: no script for preinstall, continuing
91542 silly lifecycle isarray@0.0.1~preinstall: no script for preinstall, continuing
91543 silly lifecycle q@1.5.0~preinstall: no script for preinstall, continuing
91544 silly lifecycle string_decoder@0.10.31~preinstall: no script for preinstall, continuing
91545 silly lifecycle deep-is@0.1.3~preinstall: no script for preinstall, continuing
91546 silly lifecycle delayed-stream@1.0.0~preinstall: no script for preinstall, continuing
91547 silly lifecycle combined-stream@1.0.5~preinstall: no script for preinstall, continuing
91548 silly lifecycle depd@1.1.1~preinstall: no script for preinstall, continuing
91549 silly lifecycle dom-walk@0.1.1~preinstall: no script for preinstall, continuing
91550 silly lifecycle domain-browser@1.1.7~preinstall: no script for preinstall, continuing
91551 silly lifecycle ee-first@1.1.1~preinstall: no script for preinstall, continuing
91552 silly lifecycle emojis-list@2.1.0~preinstall: no script for preinstall, continuing
91553 silly lifecycle es6-symbol@3.1.1~preinstall: no script for preinstall, continuing
91554 silly lifecycle es6-iterator@2.0.1~preinstall: no script for preinstall, continuing
91555 silly lifecycle es5-ext@0.10.24~preinstall: no script for preinstall, continuing
91556 silly lifecycle d@1.0.0~preinstall: no script for preinstall, continuing
99777 info lifecycle faye-websocket@0.10.0~install: faye-websocket@0.10.0
99778 silly lifecycle faye-websocket@0.10.0~install: no script for install, continuing
99779 silly install tiny-lr@0.2.1 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/tiny-lr-82171d6b
99780 info lifecycle tiny-lr@0.2.1~install: tiny-lr@0.2.1
99781 silly lifecycle tiny-lr@0.2.1~install: no script for install, continuing
99782 silly install which@1.0.9 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/which-0ab23225
99783 info lifecycle which@1.0.9~install: which@1.0.9
99784 silly lifecycle which@1.0.9~install: no script for install, continuing
99785 silly install grunt-legacy-util@0.2.0 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/grunt-legacy-util-aac12a82
99786 info lifecycle grunt-legacy-util@0.2.0~install: grunt-legacy-util@0.2.0
99787 silly lifecycle grunt-legacy-util@0.2.0~install: no script for install, continuing
99788 silly install which-module@1.0.0 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/which-module-6109b479
99789 info lifecycle which-module@1.0.0~install: which-module@1.0.0
99790 silly lifecycle which-module@1.0.0~install: no script for install, continuing
99791 silly install window-size@0.1.0 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/window-size-cb17406c
99792 info lifecycle window-size@0.1.0~install: window-size@0.1.0
99793 silly lifecycle window-size@0.1.0~install: no script for install, continuing
99794 silly install yargs@3.10.0 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/yargs-4bd063f5
99795 info lifecycle yargs@3.10.0~install: yargs@3.10.0
99796 silly lifecycle yargs@3.10.0~install: no script for install, continuing
99797 silly install uglify-js@2.8.29 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/uglify-js-39e58017
99798 info lifecycle uglify-js@2.8.29~install: uglify-js@2.8.29
99799 silly lifecycle uglify-js@2.8.29~install: no script for install, continuing
99800 silly install wordwrap@0.0.3 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/wordwrap-c33e9363
99801 info lifecycle wordwrap@0.0.3~install: wordwrap@0.0.3
99802 silly lifecycle wordwrap@0.0.3~install: no script for install, continuing
99803 silly install optimist@0.3.7 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/optimist-31b66ecd
99804 info lifecycle optimist@0.3.7~install: optimist@0.3.7
99805 silly lifecycle optimist@0.3.7~install: no script for install, continuing
99806 silly install uglify-js@2.2.5 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/uglify-js-85eedea8
99807 info lifecycle uglify-js@2.2.5~install: uglify-js@2.2.5
99808 silly lifecycle uglify-js@2.2.5~install: no script for install, continuing
99809 silly install wrap-ansi@2.1.0 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/wrap-ansi-d798de72
99810 info lifecycle wrap-ansi@2.1.0~install: wrap-ansi@2.1.0
99811 silly lifecycle wrap-ansi@2.1.0~install: no script for install, continuing
99812 silly install wrappy@1.0.2 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/wrappy-2cab1a45
99813 info lifecycle wrappy@1.0.2~install: wrappy@1.0.2
99814 silly lifecycle wrappy@1.0.2~install: no script for install, continuing
99815 silly install once@1.3.3 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/once-09d4653a
99816 info lifecycle once@1.3.3~install: once@1.3.3
99817 silly lifecycle once@1.3.3~install: no script for install, continuing
99818 silly install npmconf@2.1.1 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/npmconf-0109c618
99819 info lifecycle npmconf@2.1.1~install: npmconf@2.1.1
99820 silly lifecycle npmconf@2.1.1~install: no script for install, continuing
99821 silly install phantomjs@1.9.18 /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging/phantomjs-6637afa1
99822 info lifecycle phantomjs@1.9.18~install: phantomjs@1.9.18
99823 verbose lifecycle phantomjs@1.9.18~install: unsafe-perm in lifecycle true
99824 verbose lifecycle phantomjs@1.9.18~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/phantomjs/node_modules/.bin:/path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/sanaz/.local/bin:/home/sanaz/bin
99825 verbose lifecycle phantomjs@1.9.18~install: CWD: /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/phantomjs
99826 silly lifecycle phantomjs@1.9.18~install: Args: [ '-c', 'node install.js' ]
99827 silly lifecycle phantomjs@1.9.18~install: Returned: code: 1  signal: null
99828 info lifecycle phantomjs@1.9.18~install: Failed to exec install script
99829 verbose unlock done using /home/sanaz/.npm/_locks/staging-09c6fc3dce183dbc.lock for /path/to/brackets-source/needsLIBCF/brackets-release-1.12/node_modules/.staging
99830 silly rollbackFailedOptional Starting
99831 silly rollbackFailedOptional Finishing
99832 silly runTopLevelLifecycles Finishing
99833 silly install printInstalled
99834 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
99835 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
99836 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
99836 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
99836 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
99836 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
99837 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
99838 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
99839 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
99839 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
99839 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
99839 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
99840 warn Brackets@1.12.0-0 No license field.
99841 verbose If you need help, you may report this error at:
99841 verbose     <https://github.com/npm/npm/issues>
99842 verbose stack Error: phantomjs@1.9.18 install: `node install.js`
99842 verbose stack Exit status 1
99842 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
99842 verbose stack     at emitTwo (events.js:106:13)
99842 verbose stack     at EventEmitter.emit (events.js:191:7)
99842 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
99842 verbose stack     at emitTwo (events.js:106:13)
99842 verbose stack     at ChildProcess.emit (events.js:191:7)
99842 verbose stack     at maybeClose (internal/child_process.js:920:16)
99842 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
99843 verbose pkgid phantomjs@1.9.18
99844 verbose cwd /path/to/brackets-source/needsLIBCF/brackets-release-1.12
99845 error Linux 3.10.0-957.27.2.el7.x86_64
99846 error argv "/usr/bin/node" "/usr/bin/npm" "install"
99847 error node v6.17.1
99848 error npm  v3.10.10
99849 error code ELIFECYCLE
99850 error phantomjs@1.9.18 install: `node install.js`
99850 error Exit status 1
99851 error Failed at the phantomjs@1.9.18 install script 'node install.js'.
99851 error Make sure you have the latest version of node.js and npm installed.
99851 error If you do, this is most likely a problem with the phantomjs package,
99851 error not with npm itself.
99851 error Tell the author that this fails on your system:
99851 error     node install.js
99851 error You can get information on how to open an issue for this project with:
99851 error     npm bugs phantomjs
99851 error Or if that isn't available, you can get their info via:
99851 error     npm owner ls phantomjs
99851 error There is likely additional logging output above.
99852 verbose exit [ 1, true ]
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions
OS: `CentOS Linux release 7.6.1810 (Core) `
Brackets Version: `1.14`

**Comment by Chips1234** [comment]
Same issue in Windows
