### ISSUE TITLE
Edge Inspect extension still uses old preferences system

### ISSUE THREAD

**Issue by le717** [adobe/brackets#9345]
```
getPreferenceStorage is called with client ID 'C:/Users/le717/AppData/Roaming/Brackets/extensions/user/edge-inspect-extension/inspect.js,' use PreferencesManager.definePreference instead.
    at Object.getPreferenceStorage (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/preferences/PreferencesManager.js:127:32)
    at Object.<anonymous> (file:///C:/Users/le717/AppData/Roaming/Brackets/extensions/user/edge-inspect-extension/inspect.js:62:36)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86) DeprecationWarning.js:85
getValue is called to get preference 'hasShownGettingStarted,' use PreferencesManager.get instead.
    at PreferenceStorage.getValue (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/preferences/PreferenceStorage.js:128:28)
    at Object.<anonymous> (file:///C:/Users/le717/AppData/Roaming/Brackets/extensions/user/edge-inspect-extension/inspect.js:63:26)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86) 
```

I was not aware the extension is open source, so I reported it here.

Also, whenever this is fixed, if the hidden .git folder and `.DS_Store` files  can be removed from the archive, it'd download a lot quicker. :smile:

**Comment by ficristo** [comment]
@madanbn @swmitra can we close this?

**Comment by swmitra** [comment]
Yes @ficristo. We can close this issue as there are work items as part of Brackets core.
